version: '3.8'

services:
  # 1. Datenbank (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: supermarket-db
    environment:
      POSTGRES_DB: supermarket
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d supermarket"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Backend (Java 21 / Spring Boot)
  backend:
    build: ./backend
    container_name: supermarket-api
    ports:
      - "8080:8080"
    environment:
      # Wir nutzen 'db' als Hostname, da Docker das intern aufl√∂st
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/supermarket
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy

  # 3. Frontend (Angular)
  frontend:
    build: ./frontend
    container_name: supermarket-ui
    ports:
      - "4200:80"
    depends_on:
      - backend